import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AllProviders } from "@/providers";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/home/app-sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={(inter.className, "h-screen")}>
        <AllProviders>
          <SidebarProvider className="!bg-zinc-100 dark:bg-[#131315]">
            <AppSidebar />
            <SidebarInset>{children}</SidebarInset>
          </SidebarProvider>
        </AllProviders>
      </body>
    </html>
  );
}
