name: Publish Python SDK to PyPI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  pypi-publish:
    name: upload release to PyPI
    if: github.event.release && startsWith(github.event.release.tag_name, 'python-sdk-') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.repository.name }}

    defaults:
      run:
        working-directory: sdks/python

    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build package distributions to PyPI
        run: pdm build
        working-directory: sdks/python

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.3
        with:
          packages_dir: sdks/python/dist/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
